# Generated by Django 3.1.4 on 2021-05-07 09:28

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_students_stu_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.parents'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[128, 128], upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[128, 128], upload_to=''),
        ),
    ]
