# Generated by Django 3.1.4 on 2021-05-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210507_1028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenthistory',
            unique_together={('studid', 'results')},
        ),
    ]
