# Generated by Django 3.1.4 on 2021-05-11 10:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210507_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[128, 128], upload_to=''),
        ),
    ]
