# Generated by Django 3.1.4 on 2021-06-01 12:40

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
        ('school', '0007_auto_20210511_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyClassReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schclass')),
                ('session_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjects')),
                ('term_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessiontermmodel')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.damages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_bakery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_partytree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='pvno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.pv'),
        ),
        migrations.CreateModel(
            name='GeneralClassReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.schclass')),
                ('session_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.staffs')),
                ('term_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessiontermmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClassReportDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('proof', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], max_length=10)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.schclass')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.parents')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.dailyclassreport')),
                ('session_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staffs')),
                ('term_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessiontermmodel')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.company_group'),
        ),
        migrations.AddField(
            model_name='pv',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.company_group'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.company_group'),
        ),
    ]
