# Generated by Django 3.1.4 on 2021-06-06 16:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210601_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyclassreportdetails',
            name='proof',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[250, 250], upload_to=''),
        ),
    ]
