# Generated by Django 3.1.4 on 2021-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20210606_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_irishgreen',
            field=models.BooleanField(default=False),
        ),
    ]
