# Generated by Django 3.2.4 on 2021-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_profile_is_irishgreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulksend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
