# Generated by Django 3.2.4 on 2021-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_bulksend'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='activate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='extras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
