# Generated by Django 3.2.4 on 2021-06-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210626_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='venue',
        ),
    ]
