# Generated by Django 3.2.4 on 2021-06-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210626_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_sms',
            fields=[
                ('batchno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Sms_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.group_sms')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
            ],
        ),
    ]
