# Generated by Django 3.2.4 on 2021-08-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_group_sms_group_sms_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.billing')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='billing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.billing_type'),
        ),
        migrations.AddField(
            model_name='billing',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel'),
        ),
        migrations.AddField(
            model_name='billing',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students'),
        ),
        migrations.AddField(
            model_name='billing',
            name='term_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessiontermmodel'),
        ),
    ]
