# Generated by Django 3.2.4 on 2021-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210811_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Summer School', 'Summer School'), ('Weekend Care', 'Weekend Care'), ('Drop Off', 'Drop Off')], max_length=20),
        ),
    ]
