# Generated by Django 3.2.4 on 2021-08-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_students_stu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.parents'),
        ),
    ]
