# Generated by Django 3.2.4 on 2021-08-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_billing_parent_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('term_year_id', 'billing_type')},
        ),
    ]
