# Generated by Django 3.2.4 on 2021-08-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_billing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set(),
        ),
    ]
