# Generated by Django 3.2.4 on 2021-08-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_billing_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostOrder',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('customer', models.CharField(max_length=2000)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payments', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=25, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostOrder_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.hostorder')),
            ],
        ),
    ]
