# Generated by Django 3.2.4 on 2021-08-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_hostorder_hostorder_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.billing')),
            ],
        ),
    ]
