# Generated by Django 3.2.4 on 2021-09-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
