# Generated by Django 3.2.4 on 2021-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_profile_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
