# Generated by Django 3.2.4 on 2021-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_auto_20210622_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecords',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginrecords',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginrecords',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginrecords',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginrecords',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
