# Generated by Django 3.2.4 on 2021-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloginrecords',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginrecords',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
