# Generated by Django 3.2.4 on 2021-09-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_auto_20210915_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing_stocks',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damages',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclosing_stocks',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldamages',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinventory_records',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory_records',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
