# Generated by Django 3.2.4 on 2021-11-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0015_snack_detail_snacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='satus',
            new_name='status',
        ),
    ]
