# Generated by Django 3.2.4 on 2021-11-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0016_rename_satus_snacks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='snack',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bakery.snacks'),
        ),
        migrations.AddField(
            model_name='order',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakery.snacks'),
        ),
        migrations.AlterField(
            model_name='snack_detail',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.snacks'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='id',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
