# Generated by Django 3.2.4 on 2021-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0020_alter_order_snack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='activity',
            field=models.CharField(choices=[('Snack', 'Snack'), ('CEO', 'CEO')], max_length=25),
        ),
    ]
