# Generated by Django 3.2.4 on 2021-08-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-order_date',)},
        ),
        migrations.AlterField(
            model_name='categorys',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
