# Generated by Django 3.1.4 on 2022-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0002_auto_20210806_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
