# Generated by Django 3.1.4 on 2022-01-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0005_auto_20220116_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detailss',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partytree.orders'),
        ),
    ]
