# Generated by Django 3.1.4 on 2022-01-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0006_auto_20220116_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
